# Generated by Django 5.0.1 on 2024-01-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='last_image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Последние Проекты',
                'verbose_name_plural': 'Последние Проекты',
            },
        ),
    ]
