# Generated by Django 5.0.1 on 2024-01-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('plan1', models.CharField(max_length=255, verbose_name='План1')),
                ('plan2', models.CharField(max_length=255, verbose_name='План2')),
                ('plan3', models.CharField(max_length=255, verbose_name='План3')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
            },
        ),
    ]
