# Generated by Django 5.0.1 on 2024-01-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_lastblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
    ]
